services:
  backend:
    image: joshtr083/arduino-web:backend
    # Dont actually map ports, nginx will reverse proxy them
  
    environment:
      - ESP32_TOKEN=TOKEN
    volumes:
      - arduino-data:/app/data
    ports:
      - LISTEN_IP:8080
  frontend:
    image: joshtr083/arduino-web:frontend
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      # change to device ip for webpage
      - LISTEN_IP:PORT:8080
    depends_on:
      - backend

volumes:
 arduino-data:
