services:
  backend:
    image: joshtr083/arduino-web:backend
    # Dont actually map ports, use /api and /ws on frontend
    environment:
      - ESP32_TOKEN=TOKEN
    volumes:
      - arduino-data:/app/data

  frontend:
    image: joshtr083/arduino-web:frontend

    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      # change to what you want your webpage to listen on (or just do 80:8080 for public)
      - LISTEN_IP:PORT:8080
    depends_on:
      - backend

volumes:
 arduino-data:
