FROM nginx

WORKDIR /app

RUN addgroup -gid 1000 appgroup && \
    adduser --disabled-login --no-create-home --shell /bin/false -uid 1000 -ingroup appgroup appuser && \
    chown -R appuser:appgroup /var/cache/nginx && \
    chown -R appuser:appgroup /var/log/nginx && \
    chown -R appuser:appgroup /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R appuser:appgroup /var/run/nginx.pid

COPY --chown=appuser:appgroup ./dist /usr/share/nginx/html
COPY --chown=appuser:appgroup ./nginx/nginx.conf /etc/nginx/nginx.conf

USER appuser
EXPOSE 8080



